// This file is auto-generated by @hey-api/openapi-ts

export { client, type CreateClientConfig } from './client.gen';
export { type Options, RelationsManager } from './sdk.gen';
export type { ClientOptions, CreateRelationResponse, CreateRequestModel, DeleteRelationData, DeleteRelationErrors, DeleteRelationResponses, GetRelationByIdData, GetRelationByIdErrors, GetRelationByIdResponse, GetRelationByIdResponses, GetTreeItemNullData, GetTreeItemNullErrors, GetTreeItemNullResponse, GetTreeItemNullResponses, GetTreeRootData, GetTreeRootErrors, GetTreeRootResponse, GetTreeRootResponses, PagedRelationTypeTreeItemResponseModel, PaginationModelOfRelationModel, PostRelationData, PostRelationErrors, PostRelationResponse, PostRelationResponses, ReferenceByIdModel, RelationModel, RelationTypeModel, RelationTypeTreeItemResponseModel } from './types.gen';
