// This file is auto-generated by @hey-api/openapi-ts

export const CreateRelationResponseSchema = {
    required: [
        'id'
    ],
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const CreateRequestModelSchema = {
    required: [
        'parentId',
        'childId',
        'relationType'
    ],
    type: 'object',
    properties: {
        parentId: {
            type: 'string',
            format: 'uuid'
        },
        childId: {
            type: 'string',
            format: 'uuid'
        },
        relationType: {
            type: 'string',
            format: 'uuid'
        },
        comment: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const PagedRelationTypeTreeItemResponseModelSchema = {
    required: [
        'total',
        'items'
    ],
    type: 'object',
    properties: {
        total: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            description: 'Gets or sets the total number of items available.',
            format: 'int64'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/RelationTypeTreeItemResponseModel'
            },
            description: 'Gets or sets the items in the current page.'
        }
    },
    description: 'Represents a paged collection of items with total count.'
} as const;

export const PaginationModelOfRelationModelSchema = {
    required: [
        'items',
        'totalItems',
        'totalPages',
        'currentPage',
        'itemsPerPage'
    ],
    type: 'object',
    properties: {
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/RelationModel'
            }
        },
        totalItems: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        totalPages: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        currentPage: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        itemsPerPage: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const ReferenceByIdModelSchema = {
    required: [
        'id'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const RelationModelSchema = {
    required: [
        'parentId',
        'childId',
        'id',
        'createDate',
        'relationType'
    ],
    type: 'object',
    properties: {
        parentId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        childId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        comment: {
            type: [
                'null',
                'string'
            ]
        },
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        createDate: {
            type: 'string',
            format: 'date-time'
        },
        relationType: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        childName: {
            type: [
                'null',
                'string'
            ]
        },
        parentName: {
            type: [
                'null',
                'string'
            ]
        },
        childUrl: {
            type: [
                'null',
                'string'
            ]
        },
        parentUrl: {
            type: [
                'null',
                'string'
            ]
        },
        childEntityType: {
            type: [
                'null',
                'string'
            ]
        },
        parentEntityType: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const RelationTypeModelSchema = {
    required: [
        'id',
        'relations'
    ],
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        name: {
            type: [
                'null',
                'string'
            ]
        },
        alias: {
            type: [
                'null',
                'string'
            ]
        },
        parentEntityType: {
            type: [
                'null',
                'string'
            ]
        },
        childEntityType: {
            type: [
                'null',
                'string'
            ]
        },
        relations: {
            $ref: '#/components/schemas/PaginationModelOfRelationModel'
        }
    }
} as const;

export const RelationTypeTreeItemResponseModelSchema = {
    required: [
        'id',
        'hasChildren'
    ],
    type: 'object',
    properties: {
        name: {
            type: [
                'null',
                'string'
            ]
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        childObjectType: {
            type: [
                'null',
                'string'
            ],
            format: 'uuid'
        },
        parentObjectType: {
            type: [
                'null',
                'string'
            ],
            format: 'uuid'
        },
        hasChildren: {
            type: 'boolean'
        },
        parent: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/ReferenceByIdModel'
                }
            ]
        }
    }
} as const;
