// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetUmbracoRelationsmanagerApiV1TreeItemNullData, GetUmbracoRelationsmanagerApiV1TreeItemNullResponses, GetUmbracoRelationsmanagerApiV1TreeRootData, GetUmbracoRelationsmanagerApiV1TreeRootResponses, PostUmbracoRelationsmanagerApiV1RelationData, PostUmbracoRelationsmanagerApiV1RelationResponses, PostUmbracoRelationsmanagerApiV1RelationErrors, DeleteUmbracoRelationsmanagerApiV1RelationByIdData, DeleteUmbracoRelationsmanagerApiV1RelationByIdResponses, GetUmbracoRelationsmanagerApiV1RelationByIdData, GetUmbracoRelationsmanagerApiV1RelationByIdResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class RelationType {
    public static getUmbracoRelationsmanagerApiV1TreeItemNull<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoRelationsmanagerApiV1TreeItemNullData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUmbracoRelationsmanagerApiV1TreeItemNullResponses, unknown, ThrowOnError>({
            url: '/umbraco/relationsmanager/api/v1/tree/item/null',
            ...options
        });
    }
    
    public static getUmbracoRelationsmanagerApiV1TreeRoot<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoRelationsmanagerApiV1TreeRootData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUmbracoRelationsmanagerApiV1TreeRootResponses, unknown, ThrowOnError>({
            url: '/umbraco/relationsmanager/api/v1/tree/root',
            ...options
        });
    }
}

export class Relation {
    public static postUmbracoRelationsmanagerApiV1Relation<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoRelationsmanagerApiV1RelationData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostUmbracoRelationsmanagerApiV1RelationResponses, PostUmbracoRelationsmanagerApiV1RelationErrors, ThrowOnError>({
            url: '/umbraco/relationsmanager/api/v1/relation',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteUmbracoRelationsmanagerApiV1RelationById<ThrowOnError extends boolean = true>(options: Options<DeleteUmbracoRelationsmanagerApiV1RelationByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteUmbracoRelationsmanagerApiV1RelationByIdResponses, unknown, ThrowOnError>({
            url: '/umbraco/relationsmanager/api/v1/relation/{id}',
            ...options
        });
    }
}

export class RelationsManager {
    public static getUmbracoRelationsmanagerApiV1RelationById<ThrowOnError extends boolean = true>(options: Options<GetUmbracoRelationsmanagerApiV1RelationByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetUmbracoRelationsmanagerApiV1RelationByIdResponses, unknown, ThrowOnError>({
            url: '/umbraco/relationsmanager/api/v1/relation/{id}',
            ...options
        });
    }
}