// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:54813/' | (string & {});
};

export type CreateRelationResponse = {
    id: number | string;
};

export type CreateRequestModel = {
    parentId: string;
    childId: string;
    relationType: string;
    comment?: null | string;
};

export type PagedRelationTypeTreeItemResponseModel = {
    total: number | string;
    items: Array<RelationTypeTreeItemResponseModel>;
};

export type PaginationModelOfRelationModel = {
    items: Array<RelationModel>;
    totalItems: number | string;
    totalPages: number | string;
    currentPage: number | string;
    itemsPerPage: number | string;
};

export type ReferenceByIdModel = {
    id: string;
};

export type RelationModel = {
    parentId: number | string;
    childId: number | string;
    comment?: null | string;
    id: number | string;
    createDate: string;
    relationType: number | string;
    childName?: null | string;
    parentName?: null | string;
    childUrl?: null | string;
    parentUrl?: null | string;
    childEntityType?: null | string;
    parentEntityType?: null | string;
};

export type RelationTypeModel = {
    id: number | string;
    name?: null | string;
    alias?: null | string;
    parentEntityType?: null | string;
    childEntityType?: null | string;
    relations: PaginationModelOfRelationModel;
};

export type RelationTypeTreeItemResponseModel = {
    name?: null | string;
    id: string;
    childObjectType?: null | string;
    parentObjectType?: null | string;
    hasChildren: boolean;
    parent?: null | ReferenceByIdModel;
};

export type PostRelationData = {
    body: CreateRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/relationsmanager/api/v1/relation';
};

export type PostRelationErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostRelationResponses = {
    /**
     * OK
     */
    200: CreateRelationResponse;
    /**
     * Created
     */
    201: unknown;
};

export type PostRelationResponse = PostRelationResponses[keyof PostRelationResponses];

export type DeleteRelationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/umbraco/relationsmanager/api/v1/relation/{id}';
};

export type DeleteRelationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type DeleteRelationResponses = {
    /**
     * OK
     */
    200: unknown;
    /**
     * No Content
     */
    204: unknown;
};

export type GetRelationByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        page?: number | string;
        take?: number | string;
        sort?: string;
        desc?: boolean;
    };
    url: '/umbraco/relationsmanager/api/v1/relation/{id}';
};

export type GetRelationByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetRelationByIdResponses = {
    /**
     * OK
     */
    200: RelationTypeModel;
};

export type GetRelationByIdResponse = GetRelationByIdResponses[keyof GetRelationByIdResponses];

export type GetTreeItemNullData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/relationsmanager/api/v1/tree/item/null';
};

export type GetTreeItemNullErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTreeItemNullResponses = {
    /**
     * OK
     */
    200: PagedRelationTypeTreeItemResponseModel;
};

export type GetTreeItemNullResponse = GetTreeItemNullResponses[keyof GetTreeItemNullResponses];

export type GetTreeRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/relationsmanager/api/v1/tree/root';
};

export type GetTreeRootErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTreeRootResponses = {
    /**
     * OK
     */
    200: PagedRelationTypeTreeItemResponseModel;
};

export type GetTreeRootResponse = GetTreeRootResponses[keyof GetTreeRootResponses];
